services:
  web:
    depends_on:
      - postgres_db
    build:
      context: ./proyecto
      dockerfile: Dockerfile
    image: guria:latest
    ports:
      - "8000:8000"  # Map container port 8000 to host port 8000
    env_file:
      - proyecto/.env
    environment:
      - PORT:8000 # Example environment variable
    command: sh -c  "chmod +x /app/migrate.sh && sh /app/migrate.sh && /app/entrypoint.sh"

  postgres_db:
    image: postgres
    env_file:
      - proyecto/.env
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/  # Fixed volume as a list

volumes:
  postgres_data:  # Declare the named volume
